# Hardware configuration for Wilson robot

controller_manager:
  ros__parameters:
    use_sim_time: false
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController



arm_controller:
  ros__parameters:
    use_sim_time: false
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - end_effector_roll_joint
      - end_effector_yaw_joint
    interface_name: position
    
    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop: true
    allow_integration_in_goal_trajectories: true


gripper_controller:
  ros__parameters:
    use_sim_time: false
    joints:
      - gripper_left_finger_joint
      - gripper_right_finger_joint
    interface_name: position
    
    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop: true
    allow_integration_in_goal_trajectories: true

diff_drive_controller:
  ros__parameters:
    use_sim_time: false

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.235
    wheel_radius: 0.018

    use_stamped_vel: false
    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.3

    # Velocity and acceleration limits
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.min_acceleration: -1.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: false
