# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - end_effector_roll_joint
      - end_effector_yaw_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
    path_tolerance:
      joint_1: 0.1
      joint_2: 0.1
      joint_3: 0.1
      joint_4: 0.1
    goal_tolerance:
      joint_1: 0.05
      joint_2: 0.05
      joint_3: 0.05
      joint_4: 0.05
gripper_controller:
  ros__parameters:
    joints:
      - gripper_left_finger_joint
      - gripper_right_finger_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
    path_tolerance:
      gripper_left_finger_joint: 0.01
    goal_tolerance:
      gripper_left_finger_joint: 0.01